import { useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { WebView } from "react-native-webview";
import { useTheme } from "../ThemeContext";
import type { ThemeColors } from "../theme";

// The FAA's own public NOTAM Search app. There's no usable public API behind
// it — its search endpoint requires a fresh Google reCAPTCHA Enterprise
// token generated by executing their page's own JS, which isn't reproducible
// from a plain background fetch — so this embeds the real page instead, the
// same approach as the GFA map screen. It needs a live connection every
// time; there's no offline cache for a full webpage like there is for
// METAR/TAF text.
const NOTAM_URL = "https://notams.aim.faa.gov/notamSearch/nsapp.html#/";

export default function NotamScreen() {
  const { colors, spacing, fontScale } = useTheme();
  const styles = makeStyles(colors, spacing, fontScale);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);

  return (
    <View style={styles.container}>
      {failed ? (
        <View style={styles.centered}>
          <Text style={styles.errorText}>
            Couldn't load NOTAM Search. It needs a live internet connection — check again once you have signal.
          </Text>
        </View>
      ) : (
        <WebView
          source={{ uri: NOTAM_URL }}
          style={styles.webview}
          onLoadStart={() => setLoading(true)}
          onLoadEnd={() => setLoading(false)}
          onError={() => setFailed(true)}
        />
      )}
      {loading && !failed ? (
        <View style={styles.loadingOverlay}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Loading NOTAM Search…</Text>
        </View>
      ) : null}
    </View>
  );
}

function makeStyles(colors: ThemeColors, spacing: (n: number) => number, fontScale: number) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    webview: { flex: 1, backgroundColor: colors.background },
    loadingOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    loadingText: { marginTop: spacing(1.5), color: colors.textMuted, fontSize: 13 * fontScale },
    centered: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing(3) },
    errorText: { color: colors.textMuted, fontSize: 14 * fontScale, textAlign: "center" },
  });
}
